/*
 * This file is generated by jOOQ.
 */
package com.github.yaseenkadir.jbivb;


import com.github.yaseenkadir.jbivb.tables.Foobar;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.foobar</code>.
     */
    public static final Foobar FOOBAR = com.github.yaseenkadir.jbivb.tables.Foobar.FOOBAR;
}
